# Generated by Django 4.2 on 2023-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=250, verbose_name='название манги')),
                ('description', models.TextField(blank=True, verbose_name='Синопсис')),
                ('year', models.IntegerField(null=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
