# Generated by Django 4.2 on 2023-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='card',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='mangoread.genre'),
        ),
    ]
