# Generated by Django 4.2 on 2023-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoread', '0002_genre_alter_card_title_card_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
